resources:
  - name: gitrepo_res_kirti
    type: gitRepo
    repoPath: kirtisahu05/newTest
    configuration:
      integrationName: github_kirti
      branches:
        except: random
    version:
      sha: master

  - name: file_res_kirti
    type: file
    fileLocation: https://github.com/kirtisahu05/newTest/edit/master/pipelines.yml
    fileName: pipeline.yml
    configuration:
      integrationName: github_kirti
    version:
      fileDtTm: random_value

  - name: image_res_kirti
    type: image
    imageName: "library/nginx"
    configuration:
      integrationName: docker_kirti
    version:
      imageTag: latest

  - name: webhookRes
    type: webhook
    configuration:
      integrationName: docker_kirti
    version:
      payload: "asd"

  - name: clusterRes
    type: cluster
    configuration:
      integrationName: docker_kirti
      bastionHostIP: 1.2.3.4
      bastionUser: sshUser
      bastionIntegrationName: sshKeyIntegration

pipelines:
  - name: newTest_pipeline_kirti
    setup:
      runtime: onHost
    steps:
      - name: step_1
        type: bash
        configuration:
          affinityGroup: test_group
        setup:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions: [ver_7]
        requires:
          integrations:
            - docker_kirti
          resources:
            - image_res_kirti
        triggeredBy:
          resources:
            - gitrepo_res_kirti
        execution:
          onExecute:
            - echo "executing..."
        outputResources:
          # - file_res_kirti

      - name: step_2
        type: bash
        configuration:
          affinityGroup: test_group
        setup:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions: [ver_4]
        triggeredBy:
          resources:
            # - file_res_kirti
            - webhookRes
        execution:
          onExecute:
            - echo "executing..."

      - name: step_3
        type: bash
        configuration:
          affinityGroup: test_group
        setup:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions: [ver_2]
        triggeredBy:
          resources:
            # - file_res_kirti
            - webhookRes
        execution:
          onExecute:
            - echo "executing..."

      - name: step_4
        type: bash
        configuration:
          affinityGroup: test_group
        setup:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions: [ver_11]
        triggeredBy:
          resources:
            # - file_res_kirti
            - webhookRes
        execution:
          onExecute:
            - echo "executing..."

      - name: step_5
        type: bash
        configuration:
          affinityGroup: test_group
        setup:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions: [ver_9]
        triggeredBy:
          resources:
            # - file_res_kirti
            - webhookRes
        execution:
          onExecute:
            - echo "executing..."

  - name: state_pipeline
    setup:
      runtime: onHost
    steps:
      - name: stateTest
        type: bash
        configuration:
          affinityGroup: state_group
        setup:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions: [ver_5]
        triggeredBy:
          resources:
        execution:
          onExecute:
            - echo "executing..."
        outputResources:
          # - file_res_kirti
      - name: stateTest2
        type: bash
        configuration:
          affinityGroup: state_group
        setup:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions: [ver_8]
        triggeredBy:
          steps:
            - stateTest
        execution:
          onExecute:
            - echo "executing..."
        outputResources:
           # - file_res_kirti
